# Autor: Cristtopher Quintana T. <cquintana@axxezo.com>
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test