# Autor: Cristtopher Quintana T. <cquintana@axxezo.com>
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - docker login axxezo.azurecr.io -u axxezo -p Gp/THWeHCoql15kUZdig88PFf5oRWM8g
          - docker build -t axxezo.azurecr.io/papi:v1
          - docker push axxezo.azurecr.io/papi:v1
options:
  docker: true