# Autor: Cristtopher Quintana T. <cquintana@axxezo.com>
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - docker login $CONTAINER_REGISTRY_URI -u $CONTAINER_REGISTRY_USERNAME -p $CONTAINER_REGISTRY_PASSWORD
          - VERSION=v1.2
          - docker build -t $CONTAINER_REGISTRY_URI/$IMAGE_NAME:$VERSION -t $CONTAINER_REGISTRY_URI/$IMAGE_NAME:latest .
          - docker push $CONTAINER_REGISTRY_URI/$IMAGE_NAME:$VERSION
          - docker push $CONTAINER_REGISTRY_URI/$IMAGE_NAME:latest
options:
  docker: true
